### ISSUE TITLE
There is unneeded line below the hero-wave image

### ISSUE THREAD

**Issue by asafyish** [Vannsl/tailwind-landing-page-nuxt#10]
Tried solving it, but wasn't able to, looks like this:

<img width="1792" alt="line" src="https://user-images.githubusercontent.com/1331750/91305308-884aff00-e7b3-11ea-8f8e-4c990601abf1.png">
it doesn't happen in the original page from tailwindtoolbox.

**Comment by Vannsl** [comment]
Could you please add browser and OS system information?

And could you check if the webpage was scaled up or down? I can reproduce it for some steps in Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit) (macOS Catalina 10.15.6) when scaling to 90%

**Comment by asafyish** [comment]
Catalina 10.15.5:
Chrome - 85.0.4183.83
Edge - 84.0.522.63
No scaling on both browsers, but on different zoom levels, the line can disappear.

Doesn't happen in Firefox though.

**Comment by Vannsl** [comment]
Thanks!

The difference between the original tailwind landingpage and my nuxt implementation is that they use inline svg and I an image tage with the svg file. I will check what's going on there. Thanks for the hint.

**Comment by Vannsl** [comment]
Sorry for the delay, I'm working on it.

**Comment by asafyish** [comment]
I was able to fix it by editing hero-wave.svg, changing viewBox="0 0 1428 174" to viewBox="0 0 1428 172"

**Comment by Vannsl** [comment]
Hi @asafyish,

that's awesome. Do you want to create a PR for that?
