### ISSUE TITLE
Could not load Hero image

### ISSUE THREAD

**Issue by Vannsl** [Vannsl/tailwind-landing-page-nuxt#6]
The image of the hero container could not be load.

## Expected Behavior
An illustration should be visible in the hero container. On desktop it should be on the right side next to the text. On mobile it should be on the bottom of the container.

## Current Behavior
The image could not be found.  The src is `[object Module]`.

## Possible Solution
This happens since the latest upgrade of the packages, commit [8a995538](https://github.com/Vannsl/tailwind-landing-page-nuxt/commit/8a995538610c599903ca4fb8bc7d73693af77b1b). The image is located in the assets folder of next. The assets of this folder run through a webpack process. It works for other illustrations, like the first one below the header container which has the source: `/_nuxt/98c6400aa097bf552dded8b9162d99d3.svg`.

## Steps to Reproduce
Production:
1. Go to https://tailwind-landing-page-nuxt.netlify.app/#

Localhost:
1. Clone the repo
2. npm i
3. npm run dev
4. Go to http://localhost:3000/

## Detailed Description
The code can be found in the file `components/Hero`, line 5.

**Comment by lockinmarv** [comment]
Could not reproduce, images are there (`hero.png` and `hero-wave.svg` are properly loaded).

**Comment by Vannsl** [comment]
Thanks for checking.  You‘re right, hero-wave.svg wasn’t the problem. It seems to be the png (I’m on mobile right now and can’t check). 

Here’s a screenshot from mobile safari:

![77C718BE-3A9A-4150-A60A-86C5CD3D10C7](https://user-images.githubusercontent.com/5849721/87871862-67251080-c9b4-11ea-938e-98d92272f33b.png)

**Comment by hajimetakase** [comment]
I'm having same issues. 'png' of img tag become src="[object Module]" in browser.  'svg' files are fine. Maybe the problem of @nuxtjs/svg?

**Comment by hajimetakase** [comment]
I think it is simply because I forgot to add `slot="png"` in img tag.

**Comment by Vannsl** [comment]
The PR fixes the issue, feel free to review.
